org: mesheo
app: google-reviews-analyzer
service: google-reviews-analyzer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    timeout: 30
    handler: index.handler
    memorySize: 1024
    events:
      - httpApi:
          path: /
          method: get