org: mesheo
app: google-reviews-analyzer
service: google-reviews-analyzer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

functions:
  api:
    timeout: 30
    handler: index.handler
    memorySize: 1024
    events:
      - httpApi:
          path: /
          method: get
  

resources:
  Resources:
    ScrapeRequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: scrape-request-queue.fifo
        ContentBasedDeduplication: true
        FifoQueue: true
        VisibilityTimeout: 30
        DelaySeconds: 0