org: mesheo
app: google-reviews-analyzer
service: google-reviews-analyzer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

functions:
  scrapeRequest:
    timeout: 30
    memorySize: 128
    handler: src/functions/scrapeRequest.handler
    iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: arn:aws:sqs:sa-east-1:521101151519:scrape-request-queue.fifo
    events:
      - httpApi:
          path: /scrapeRequest
          method: post

  runScraper:
    timeout: 90
    memorySize: 1024
    handler: src/functions/runScraper.handler
    events:
      - sqs: arn:aws:sqs:sa-east-1:521101151519:scrape-request-queue.fifo
      - httpApi:
          path: /
          method: get

resources:
  Resources:
    ScrapeRequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: scrape-request-queue.fifo
        ContentBasedDeduplication: true
        FifoQueue: true
        VisibilityTimeout: 150
        DelaySeconds: 5

# Outputs:
#   ScrapeRequestQueueUrl:
#     Value: arn:aws:sqs:sa-east-1:521101151519:scrape-request-queue.fifo
#     Export:
#       Name: ScrapeRequest-QueueUrl